name: screenplay-api-tests
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 10 * * 6'  # Run every Sunday at 7 AM UTC

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Execute regression testes
        run: mvn verify

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: site-artifact
          path: target/site/serenity/index.html